name: Header Bidding Solution
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build Prebid.js
        run: npm run build
      - name: Deploy to Server
        run: ./deploy.sh
